package com.ib.quest;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;

import javax.imageio.ImageIO;
import javax.swing.JEditorPane;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;

import net.sourceforge.jeuclid.MathMLParserSupport;
import net.sourceforge.jeuclid.context.LayoutContextImpl;
import net.sourceforge.jeuclid.converter.Converter;
import net.sourceforge.jeuclid.swing.JMathComponent;
import uk.ac.ed.ph.snuggletex.SnuggleEngine;
import uk.ac.ed.ph.snuggletex.SnuggleInput;
import uk.ac.ed.ph.snuggletex.SnuggleSession;

/**
 * Parses strings within the html file to get the desired effect
 * 
 * @author Andrew Wang
 * @version 1.0.4.9
 */
public class Parser {

	/**
	 * Starts the Snuggle Engine
	 */
	private static final SnuggleEngine SE = new SnuggleEngine();
	
	/**
	 * Parses a string and formats it so it becomes a {@link JMathComponent}
	 * 
	 * @param txt
	 * The Latex
	 * @param name
	 * Name of Image
	 * 
	 * @return
	 * The new image {@link File}
	 */
	private static final File mkMath(String txt, String name) {
		// Image File
		File img = null;
		// Creates New Session
		SnuggleSession sS = SE.createSession();
		// Creates Image
		try {
			// Creation
			sS.parseInput(new SnuggleInput(txt));
			// Make Image
			BufferedImage bi = Converter.getInstance().render(
					MathMLParserSupport.parseString(sS.buildXMLString()), 
					LayoutContextImpl.getDefaultLayoutContext());
			// Save Image
			ImageIO.write(bi, "png", img = new File(Main.TEMP.getPath() + "\\" + name + ".png"));
			// Temp
			img.deleteOnExit();
		} catch (IOException | SAXException | ParserConfigurationException e) {}
		// Give back
		return img;
	}
	
	/**
	 * Reads a line and converts it to a {@link JPanel} of {@link JLabel} and {@link JMathComponent}
	 * 
	 * @param txt
	 * The String in question
	 * @param ID
	 * Question ID
	 * 
	 * @return
	 * The JPanel
	 */
	public static final JEditorPane parseTxt(String txt, String ID) {
		// Container
		JEditorPane lbl = null;
		// If does not contain Latex, return
		if(!txt.contains("\\(") && !txt.contains("\\[") && !txt.contains("$$")) {
			// Text
			lbl = new JEditorPane("text/html", txt);
			lbl.setBackground(new Color(240, 240, 240));
			lbl.setEditable(false);
			// Size
			return lbl;
		}
		// Parse txt
		boolean isMath = false;
		String display = "";
		int imgC = 0;
		for(String chunk : (" " + txt).split("(\\\\\\(|\\\\\\[|\\$\\$|\\\\\\]|\\\\\\))")) {
			// Skip First Block if just space
			if(chunk.equals(" ")) {
				isMath = true;
				continue;
			}
			// Filter the Math stuff
			if(isMath) {
				try {
					File img = mkMath("\\[" + chunk + "\\]", "LAT-" + ID + "-" + imgC);
					display += "<img src='" + img.toURI().toURL() + "'></img>";
					imgC++;
				} catch (MalformedURLException e) {}
			}else
				display += chunk;
			// Switching
			isMath = !isMath;
		}
		// TODO Try and use this to display image generated by Converter and hold text.
		lbl = new JEditorPane("text/html", display);
		lbl.setBackground(new Color(240, 240, 240));
		lbl.setEditable(false);
		// Size
		return lbl;
	}
}
